#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1="\[\033[0;32m\]\W ➟ \[\033[0m\]"

new_line_flag=0
function set_new_line() {
    if [ "$new_line_flag" -eq 1 ]; then
        echo "" # leave empty line
    else
        new_line_flag=1
    fi
}
PROMPT_COMMAND=set_new_line

# for GENTOO
# alias emerge="emerge --ask --verbose"
# alias update="sudo emerge --sync"
# alias upgrade="sudo emerge --ask --verbose --update --deep --newuse @world"
# alias uninstall="sudo emerge --deselect"
# alias autoremove="sudo emerge --verbose --depclean"
# alias cleanup="sudo eclean packages && sudo eclean distfiles"
# alias list-packages="bat /var/lib/portage/world"

# for ARCH
alias install="sudo pacman -S "
alias uninstall="sudo pacman -R "
alias upgrade="sudo pacman -Syu"

# general
alias free="free -m"
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"
alias ping="ping -c 3 gentoo.org"
alias updatedb="sudo updatedb"
alias git-token="cat ~/Files/Git/token"
alias ristretto="ristretto ."

alias cat="bat"
alias ls="eza --icons --sort ext --group-directories-first"
alias lsc="clear && eza --icons --sort ext --group-directories-first"
alias ll="eza --icons --sort ext -l --group-directories-first"
alias llc="clear && eza --icons --sort ext -l --group-directories-first"
alias rm="trash-put"
alias acpi="acpi | grep -oE '[0-9]+%' | cut -d '%' -f 1"

# python
alias python="~/.config/python_venv/bin/python"
alias py="~/.config/python_venv/bin/python"
alias pip="~/.config/python_venv/bin/pip"